/**
 * MaterialQuickAddDialog Component
 * Main orchestrator for two-step material creation flow
 */

import React, { useState, useEffect } from 'react';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from './ui/dialog';
import { MaterialTypeSelector } from './material-quick-add/MaterialTypeSelector';
import { DynamicMaterialForm } from './material-quick-add/DynamicMaterialForm';
import { getMaterialConfig } from '../config/material-quick-add.config';
import type { MaterialDomain, MaterialFormData, CreatedMaterial } from '../types/material-quick-add.types';
import { notify } from '../lib/notify';

interface MaterialQuickAddDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  materialDomain: MaterialDomain;
  onMaterialCreated: (material: CreatedMaterial) => void;
  initialType?: string;
}

export const MaterialQuickAddDialog: React.FC<MaterialQuickAddDialogProps> = ({
  open,
  onOpenChange,
  materialDomain,
  onMaterialCreated,
  initialType,
}) => {
  const [step, setStep] = useState<1 | 2>(1);
  const [selectedType, setSelectedType] = useState<string | null>(initialType || null);
  const [formData, setFormData] = useState<MaterialFormData>({});
  const [saving, setSaving] = useState(false);

  // Reset state when dialog opens with initialType
  useEffect(() => {
    if (open && initialType) {
      setSelectedType(initialType);
      // If initialType is provided, we could optionally skip to step 2
      // For now, we keep step 1 so users can see all options
    }
  }, [open, initialType]);

  const handleSelectType = (type: string) => {
    setSelectedType(type);
    setStep(2);
  };

  const handleBack = () => {
    setStep(1);
    // Preserve selectedType and formData when going back
  };

  const handleSave = async () => {
    // Only validate material type selection
    if (!selectedType) {
      notify.error('Please select a material type');
      return;
    }

    const config = getMaterialConfig(selectedType);
    if (!config) {
      notify.error('Invalid material type');
      return;
    }

    setSaving(true);
    try {
      // Prepare payload - remove name if not manually edited to trigger auto-generation
      const payload = { ...formData };

      // If name wasn't manually edited or is empty, remove it to trigger backend auto-generation
      if (!formData._nameManuallyEdited || !formData.name?.trim()) {
        delete payload.name;
        delete payload[config.nameField]; // Remove type-specific name field too
      }

      // Remove internal tracking flag
      delete payload._nameManuallyEdited;

      // Call the type-specific service function
      const result = await config.createService(payload);

      // Extract created material details
      const newMaterial: CreatedMaterial = {
        id: result.id,
        code: result[config.codeField],
        name: result[config.nameField], // This will be auto-generated by backend if name was empty
        color: formData.color || null,
        ...result, // Include all other fields
      };

      // Callback to parent component
      onMaterialCreated(newMaterial);

      // Close dialog and reset state
      onOpenChange(false);
      resetState();

      notify.success(`${newMaterial.name} created and added successfully`);
    } catch (error: any) {
      console.error('Failed to create material:', error);
      const errorMessage = error?.response?.data?.message || 'Failed to create item';
      notify.error(errorMessage);
    } finally {
      setSaving(false);
    }
  };

  const resetState = () => {
    setStep(1);
    setSelectedType(null);
    setFormData({});
  };

  const handleClose = () => {
    onOpenChange(false);
    // Reset state after a short delay to allow dialog close animation
    setTimeout(resetState, 200);
  };

  const config = selectedType ? getMaterialConfig(selectedType) : null;

  return (
    <Dialog open={open} onOpenChange={handleClose}>
      <DialogContent className="max-w-3xl max-h-[90vh] overflow-hidden flex flex-col">
        <DialogHeader>
          <DialogTitle>
            {step === 1 ? 'Add New Material' : config ? `Add New ${config.label}` : 'Add Material'}
          </DialogTitle>
        </DialogHeader>

        <div className="flex-1 overflow-y-auto">
          {step === 1 && (
            <MaterialTypeSelector domain={materialDomain} selectedType={selectedType} onSelectType={handleSelectType} />
          )}

          {step === 2 && config && (
            <DynamicMaterialForm
              config={config}
              formData={formData}
              onChange={setFormData}
              onBack={handleBack}
              onSave={handleSave}
              saving={saving}
            />
          )}
        </div>
      </DialogContent>
    </Dialog>
  );
};

export default MaterialQuickAddDialog;
