// Import Service - Handles CSV and Excel imports with validation
import csv from 'csv-parser';
import ExcelJS from 'exceljs';
import { Readable } from 'stream';
import fs from 'fs';
import { z } from 'zod';

export interface ImportColumn {
  fieldName: string;
  displayName: string;
  required?: boolean;
  type?: 'text' | 'number' | 'date' | 'boolean' | 'email';
  validator?: z.ZodType<unknown>;
  autoGenerated?: boolean;
}

export interface ImportOptions {
  columns: ImportColumn[];
  file: Express.Multer.File;
  maxRows?: number;
}

/**
 * Zip-bomb / DoS guards for spreadsheet imports.
 *
 * A small compressed .xlsx can decompress into a workbook with millions of
 * rows/cells and exhaust memory during parse. We defend at two levels:
 *  - MAX_IMPORT_FILE_BYTES: reject oversized uploads before we ever read them
 *    (redundant with the multer limit, but also guards non-HTTP callers).
 *  - MAX_IMPORT_CELLS / MAX_IMPORT_ROWS: after the sheet dimensions are known,
 *    abort BEFORE the O(rows*cols) validation loop if the sheet is absurdly big.
 */
const MAX_IMPORT_FILE_BYTES = 10 * 1024 * 1024; // 10MB (mirrors upload middleware)
const MAX_IMPORT_ROWS = 50_000; // hard ceiling on declared sheet rows
const MAX_IMPORT_CELLS = 1_000_000; // hard ceiling on rows * columns

/**
 * Reject an upload whose raw size exceeds the hard limit, before parsing.
 */
function assertFileSizeWithinLimit(file: Express.Multer.File): void {
  if (typeof file.size === 'number' && file.size > MAX_IMPORT_FILE_BYTES) {
    throw new Error(`File too large. Maximum import size is ${Math.floor(MAX_IMPORT_FILE_BYTES / (1024 * 1024))}MB.`);
  }
}

/**
 * Get readable stream from file - supports both buffer and disk storage
 */
function getFileStream(file: Express.Multer.File): Readable {
  if (file.buffer) {
    // Memory storage - create stream from buffer
    return Readable.from(file.buffer);
  } else if (file.path) {
    // Disk storage - create read stream from file path
    return fs.createReadStream(file.path);
  }
  throw new Error('File has neither buffer nor path');
}

export interface ImportResult {
  success: boolean;
  totalRows: number;
  validRows: number;
  invalidRows: number;
  errors: ImportError[];
  data?: Record<string, unknown>[];
}

export interface ImportError {
  row: number;
  field?: string;
  message: string;
  value?: unknown;
}

class ImportService {
  /**
   * Import data from CSV file
   */
  async importFromCSV(options: ImportOptions): Promise<ImportResult> {
    const { columns, file, maxRows = 10000 } = options;

    // Reject oversized uploads before streaming/parsing (DoS guard).
    assertFileSizeWithinLimit(file);

    return new Promise((resolve, reject) => {
      const results: Record<string, unknown>[] = [];
      const errors: ImportError[] = [];
      let rowNumber = 0;
      let isFirstDataRow = true;
      let skipIndicatorRow = false;

      const stream = getFileStream(file);

      stream
        .pipe(csv())
        .on('data', (row) => {
          rowNumber++;

          // Check if first data row is a Required/Optional indicator row
          if (isFirstDataRow) {
            isFirstDataRow = false;
            const values = Object.values(row) as unknown[];
            const isIndicatorRow = values.every((val) => {
              const normalized = (val || '').toString().toLowerCase().trim();
              return (
                normalized === '' ||
                normalized === 'required' ||
                normalized === 'optional' ||
                normalized === 'auto-generated'
              );
            });
            if (isIndicatorRow) {
              skipIndicatorRow = true;
              return; // Skip this row
            }
          }

          if (rowNumber > maxRows + (skipIndicatorRow ? 1 : 0)) {
            return; // Stop processing after max rows
          }

          const { valid, data, rowErrors } = this.validateRow(row, columns, rowNumber);

          if (valid) {
            results.push(data);
          } else {
            errors.push(...rowErrors);
          }
        })
        .on('end', () => {
          resolve({
            success: errors.length === 0,
            totalRows: rowNumber - (skipIndicatorRow ? 1 : 0),
            validRows: results.length,
            invalidRows: errors.length,
            errors,
            data: results,
          });
        })
        .on('error', (error) => {
          reject(error);
        });
    });
  }

  /**
   * Import data from Excel file
   */
  async importFromExcel(options: ImportOptions): Promise<ImportResult> {
    const { columns, file, maxRows = 10000 } = options;

    // Reject oversized uploads before parsing the (potentially zip-bombed) file.
    assertFileSizeWithinLimit(file);

    const workbook = new ExcelJS.Workbook();

    // Support both buffer and disk storage
    if (file.buffer) {
      // Cast to handle Buffer/ArrayBuffer type differences between Node versions
      await workbook.xlsx.load(file.buffer as unknown as ArrayBuffer);
    } else if (file.path) {
      await workbook.xlsx.readFile(file.path);
    } else {
      throw new Error('File has neither buffer nor path');
    }

    const worksheet = workbook.worksheets[0]; // Get first sheet
    if (!worksheet) {
      throw new Error('No worksheet found in Excel file');
    }

    // Abort before the O(rows*cols) validation loop if the sheet is absurdly
    // large (zip-bomb / accidental huge export). rowCount/columnCount reflect
    // the declared sheet dimensions.
    const declaredRows = worksheet.rowCount || 0;
    const declaredCols = worksheet.columnCount || 0;
    if (declaredRows > MAX_IMPORT_ROWS || declaredRows * declaredCols > MAX_IMPORT_CELLS) {
      throw new Error(
        `Spreadsheet too large to import (${declaredRows} rows x ${declaredCols} columns). ` +
          `Limit is ${MAX_IMPORT_ROWS} rows / ${MAX_IMPORT_CELLS} cells. Split the file and retry.`
      );
    }

    const results: Record<string, unknown>[] = [];
    const errors: ImportError[] = [];

    // Get header row (assume row 1)
    const headerRow = worksheet.getRow(1);
    const headers: string[] = [];
    headerRow.eachCell((cell, colNumber) => {
      headers[colNumber] = cell.value?.toString() || '';
    });

    // Check if second row is a Required/Optional indicator row
    let dataStartRow = 2;
    if (worksheet.rowCount >= 2) {
      const secondRow = worksheet.getRow(2);
      let isIndicatorRow = true;
      secondRow.eachCell((cell) => {
        const normalized = (cell.value || '').toString().toLowerCase().trim();
        if (
          normalized !== '' &&
          normalized !== 'required' &&
          normalized !== 'optional' &&
          normalized !== 'auto-generated'
        ) {
          isIndicatorRow = false;
        }
      });
      if (isIndicatorRow) {
        dataStartRow = 3; // Skip the indicator row
      }
    }

    // Process data rows
    let validRowCount = 0;
    worksheet.eachRow((row, rowNumber) => {
      if (rowNumber < dataStartRow) return; // Skip header and indicator row
      if (validRowCount >= maxRows) return; // Stop after max rows

      const rowData: Record<string, unknown> = {};
      row.eachCell((cell, colNumber) => {
        const header = headers[colNumber];
        rowData[header] = cell.value;
      });

      const { valid, data, rowErrors } = this.validateRow(rowData, columns, rowNumber);

      if (valid) {
        results.push(data);
        validRowCount++;
      } else {
        errors.push(...rowErrors);
      }
    });

    return {
      success: errors.length === 0,
      totalRows: worksheet.rowCount - (dataStartRow - 1), // Exclude header and indicator row
      validRows: results.length,
      invalidRows: errors.length,
      errors,
      data: results,
    };
  }

  /**
   * Preview import data (first 100 rows)
   */
  async previewImport(options: ImportOptions): Promise<ImportResult> {
    const previewOptions = { ...options, maxRows: 100 };

    const fileExtension = options.file.originalname.split('.').pop()?.toLowerCase();

    if (fileExtension === 'csv') {
      return this.importFromCSV(previewOptions);
    } else if (fileExtension === 'xlsx' || fileExtension === 'xls') {
      return this.importFromExcel(previewOptions);
    } else {
      throw new Error('Unsupported file format. Please use CSV or Excel files.');
    }
  }

  /**
   * Validate a single row of data
   */
  private validateRow(
    row: Record<string, unknown>,
    columns: ImportColumn[],
    rowNumber: number
  ): { valid: boolean; data: Record<string, unknown>; rowErrors: ImportError[] } {
    const errors: ImportError[] = [];
    const validatedData: Record<string, unknown> = {};

    columns.forEach((column) => {
      // Try matching with and without (Required)/(Optional)/(Auto-generated) suffix
      let headerWithSuffix = '';
      if (column.autoGenerated) {
        headerWithSuffix = column.displayName + ' (Auto-generated)';
      } else if (column.required) {
        headerWithSuffix = column.displayName + ' (Required)';
      } else {
        headerWithSuffix = column.displayName + ' (Optional)';
      }
      let value = row[headerWithSuffix] !== undefined ? row[headerWithSuffix] : row[column.displayName];

      // Check required fields
      if (column.required && (value === null || value === undefined || value === '')) {
        errors.push({
          row: rowNumber,
          field: column.displayName,
          message: `${column.displayName} is required`,
          value,
        });
        return;
      }

      // Type validation
      if (value !== null && value !== undefined && value !== '') {
        const typeError = this.validateType(value, column.type);
        if (typeError) {
          errors.push({
            row: rowNumber,
            field: column.displayName,
            message: typeError,
            value,
          });
          return;
        }

        // Custom validator (Zod schema)
        if (column.validator) {
          try {
            const parsedValue = column.validator.parse(value);
            validatedData[column.fieldName] = parsedValue;
          } catch (error: unknown) {
            const zodError = error as { errors?: Array<{ message?: string }> };
            errors.push({
              row: rowNumber,
              field: column.displayName,
              message: zodError.errors?.[0]?.message || 'Validation failed',
              value,
            });
            return;
          }
        } else {
          validatedData[column.fieldName] = this.convertType(value, column.type);
        }
      } else {
        validatedData[column.fieldName] = null;
      }
    });

    return {
      valid: errors.length === 0,
      data: validatedData,
      rowErrors: errors,
    };
  }

  /**
   * Validate value type
   */
  private validateType(value: unknown, type?: string): string | null {
    if (!type) return null;

    switch (type) {
      case 'number':
        if (isNaN(Number(value))) {
          return `Must be a valid number`;
        }
        break;
      case 'email':
        const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
        if (!emailRegex.test(String(value))) {
          return `Must be a valid email address`;
        }
        break;
      case 'date':
        if (isNaN(Date.parse(String(value)))) {
          return `Must be a valid date`;
        }
        break;
      case 'boolean':
        const boolValue = String(value).toLowerCase();
        if (!['true', 'false', '1', '0', 'yes', 'no'].includes(boolValue)) {
          return `Must be a boolean value (true/false, yes/no, 1/0)`;
        }
        break;
    }

    return null;
  }

  /**
   * Convert value to appropriate type
   */
  private convertType(value: unknown, type?: string): unknown {
    if (!type || value === null || value === undefined) return value;

    switch (type) {
      case 'number':
        return Number(value);
      case 'date':
        return new Date(String(value));
      case 'boolean':
        const convertBoolValue = String(value).toLowerCase();
        return ['true', '1', 'yes'].includes(convertBoolValue);
      default:
        return value;
    }
  }

  /**
   * Generate CSV template for a module
   */
  generateTemplate(columns: ImportColumn[]): string {
    // Header row with column names only
    const headers = columns.map((col) => col.displayName);

    // Required/Optional indicator row
    const indicators = columns.map((col) => {
      if (col.autoGenerated) {
        return 'Auto-generated';
      } else if (col.required) {
        return 'Required';
      } else {
        return 'Optional';
      }
    });

    return headers.join(',') + '\n' + indicators.join(',') + '\n';
  }

  /**
   * Generate Excel template for a module
   */
  async generateExcelTemplate(columns: ImportColumn[], moduleName: string): Promise<Buffer> {
    const workbook = new ExcelJS.Workbook();
    const worksheet = workbook.addWorksheet('Import Template');

    // Add header row with column names only
    const headerRow = worksheet.addRow(columns.map((col) => col.displayName));
    headerRow.font = { bold: true, color: { argb: 'FFFFFFFF' } };
    headerRow.fill = {
      type: 'pattern',
      pattern: 'solid',
      fgColor: { argb: 'FF4472C4' },
    };

    // Add Required/Optional indicator row (Row 2)
    const indicatorRow = worksheet.addRow(
      columns.map((col) => {
        if (col.autoGenerated) {
          return 'Auto-generated';
        } else if (col.required) {
          return 'Required';
        } else {
          return 'Optional';
        }
      })
    );
    indicatorRow.font = { italic: true, color: { argb: 'FF666666' } };
    indicatorRow.fill = {
      type: 'pattern',
      pattern: 'solid',
      fgColor: { argb: 'FFF0F0F0' },
    };

    // Data rows start from row 3

    // Set column widths
    worksheet.columns = columns.map((col, index) => ({
      key: col.fieldName,
      width: 20,
    }));

    // Add instructions sheet
    const instructionsSheet = workbook.addWorksheet('Instructions');
    instructionsSheet.addRow(['Import Template Instructions']);
    instructionsSheet.getRow(1).font = { size: 14, bold: true };
    instructionsSheet.addRow([]);
    instructionsSheet.addRow([
      '1. Fill in your data starting from row 3 (row 2 contains Required/Optional indicators)',
    ]);
    instructionsSheet.addRow(['2. Do not modify the header row (row 1) or indicator row (row 2)']);
    instructionsSheet.addRow(['3. Fill in all required fields']);
    instructionsSheet.addRow(['4. Save the file and upload for import']);
    instructionsSheet.addRow([]);
    instructionsSheet.addRow(['Column Definitions:']);
    instructionsSheet.getRow(8).font = { bold: true };

    columns.forEach((col, index) => {
      let status = 'Optional';
      if (col.autoGenerated) {
        status = 'Auto-generated';
      } else if (col.required) {
        status = 'Required';
      }
      instructionsSheet.addRow([col.displayName, status, col.type || 'text']);
    });

    const buffer = await workbook.xlsx.writeBuffer();
    return Buffer.from(buffer);
  }
}

export default new ImportService();
