/**
 * Single shared icon map for all navigation surfaces (Sidebar, CommandPalette).
 * Every `iconName` referenced in navigation.ts MUST exist here — enforced by
 * src/config/__tests__/navigation.test.ts. Chrome icons (chevrons, search,
 * star, close) are NOT part of this map; components import those directly.
 */
import {
  Activity,
  AlertTriangle,
  BarChart3,
  Beaker,
  BookImage,
  BookOpen,
  Box,
  Bug,
  Building2,
  Calculator,
  Calendar,
  CheckSquare,
  ClipboardCheck,
  ClipboardList,
  Cog,
  Database,
  Factory,
  FileBarChart,
  FileSpreadsheet,
  FileText,
  FlaskConical,
  FolderTree,
  Hand,
  Hash,
  Layers,
  LayoutDashboard,
  Link2,
  ListChecks,
  Lock,
  MessageCircle,
  Package,
  PackageCheck,
  PackageOpen,
  PackagePlus,
  PackageSearch,
  PackageX,
  Palette,
  Puzzle,
  QrCode,
  Receipt,
  Ruler,
  Scale,
  Scissors,
  Send,
  Settings,
  ShieldAlert,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Shuffle,
  Sparkles,
  Tag,
  TestTube,
  Truck,
  Upload,
  UserCheck,
  UserCircle,
  Users,
  Wallet,
  Warehouse,
  Waves,
} from 'lucide-react';

export type NavIconComponent = React.ComponentType<{ className?: string }>;

export const NAV_ICON_MAP: Record<string, NavIconComponent> = {
  Activity,
  AlertTriangle,
  BarChart3,
  Beaker,
  BookImage,
  BookOpen,
  Box,
  Bug,
  Building2,
  Calculator,
  Calendar,
  CheckSquare,
  ClipboardCheck,
  ClipboardList,
  Cog,
  Database,
  Factory,
  FileBarChart,
  FileSpreadsheet,
  FileText,
  FlaskConical,
  FolderTree,
  Hand,
  Hash,
  Layers,
  LayoutDashboard,
  Link2,
  ListChecks,
  Lock,
  MessageCircle,
  Package,
  PackageCheck,
  PackageOpen,
  PackagePlus,
  PackageSearch,
  PackageX,
  Palette,
  Puzzle,
  QrCode,
  Receipt,
  Ruler,
  Scale,
  Scissors,
  Send,
  Settings,
  ShieldAlert,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Shuffle,
  Sparkles,
  Tag,
  TestTube,
  Truck,
  Upload,
  UserCheck,
  UserCircle,
  Users,
  Wallet,
  Warehouse,
  Waves,
};

export function getNavIconComponent(name: string): NavIconComponent | null {
  const Icon = NAV_ICON_MAP[name];
  if (!Icon) {
    if (import.meta.env.DEV) {
      console.warn(`[nav-icons] Unmapped icon name "${name}" — add it to NAV_ICON_MAP`);
    }
    return null;
  }
  return Icon;
}
