-- Add specific trim PO categories to POCategory enum
ALTER TYPE "POCategory" ADD VALUE IF NOT EXISTS 'BUTTON';
ALTER TYPE "POCategory" ADD VALUE IF NOT EXISTS 'ZIPPER';
ALTER TYPE "POCategory" ADD VALUE IF NOT EXISTS 'ELASTIC';
ALTER TYPE "POCategory" ADD VALUE IF NOT EXISTS 'LABEL';
ALTER TYPE "POCategory" ADD VALUE IF NOT EXISTS 'PACKAGING';
ALTER TYPE "POCategory" ADD VALUE IF NOT EXISTS 'MACHINE_PART';
ALTER TYPE "POCategory" ADD VALUE IF NOT EXISTS 'OTHER_MATERIAL';
